POST /users/register HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Content-Length: 107

{
    "email": "Cristopher.Kling94@yahoo.com",
    "username": "johnd",
    "password": "7byBLB69rupsxgq"
}